### PR TITLE
Curve: symlink to generic name

### PR DESCRIPTION
**Pull request by uwe**
Fixes DE-17

Different chains (e. g. Polygon or Arbitrum) might not have the exact same symbols as mainnet. Also, PoolX4 is only used on mainnet. With this PR we have a workaround for both situations.

This PR is a blocker for all non-Ethereum chains.

### CODE REVIEW

**Comment by dhruvinparikh** [comment]
- Fix merge conflicts.

**Review by dhruvinparikh — APPROVED** [review]
It is not at all wrong to treat same protocol on different chains as am independent protocol. It was possible in Curve which is fine however it might not be feasible for other future protocols

**Comment by uwe** [comment]
I'm afraid this will happen at some point. But for now it seems to hold: Kuririn does not need code changes for Aave on Polygon.

**Comment by undermethod** [comment]
Please see #36

**Comment by uwe** [comment]
@undermethod @deepcrazy @leodinh any opinion on this approach? This PR is blocking 4 tickets (2 of them basically ready to go) for all the Curve subgraphs on different chains.

**Review by undermethod — DISMISSED** [review]
After resolving conflicts from #37, this should be good to go!

**Review by dhruvinparikh — APPROVED** [review]

**Review by undermethod — APPROVED** [review]

**Review by deepcrazy — APPROVED** [review]

**Pull request merged**
