### PR TITLE
[DE-3] Aave subgraph on Polygon

### PR DESCRIPTION
**Pull request by kuririn1**
Fixes DE-3

Aave subgraph on Polygon

### CODE REVIEW

**Comment by uwe** [comment]
What were the differences to `AaveV2` on mainnet?

**Comment by kuririn1** [comment]
> What were the differences to `AaveV2` on mainnet?

It's identical - subgraph code didn't require any changes (maybe only one for importing some code, but it was only cosmetic change). Only the addresses changed.

**Comment by uwe** [comment]
Let's talk with @dhruvinparikh tomorrow if copying it is then the right approach. I don't think so. It will lead to an unmaintainable repo.

**Review by dhruvinparikh — APPROVED** [review]
`src/ethereum/` for Ethereum subhraphs
`src/polygon/` for Polygon subgraphs

**Review by deepcrazy — CHANGES_REQUESTED** [review]
Agree with @dhruvinparikh's point of segregating `src` into `src/ethereum`, `src/polygon` and soon..

**Comment by uwe** [comment]
@kuririn1 I had something like #42 in mind for Aave. No (or minimal) code changes, just config (and the symlinks).

**Comment by kuririn1** [comment]
> @kuririn1 I had something like #42 in mind for Aave. No (or minimal) code changes, just config (and the symlinks).

Ok, great - I will look into it. I know it's possible to do with config alone (only one constant could be a problem - but maybe it's the symlinks you are talking about and it could be solved easily too).

**Comment by uwe** [comment]
@kuririn1 we now have rewards for AaveV2 - are there also rewards for Polygon?

**Comment by kuririn1** [comment]
> @kuririn1 we now have rewards for AaveV2 - are there also rewards for Polygon?

Yes, it will be the same code - I just need to restructure the code, like we talked last time and I will add it.

**Comment by uwe** [comment]
I'm no longer convinced that it will work. The `process.env.CONFIG` thing should break, because in the `graph-cli` context this is not set (it is transformed to WASM and running on the graph node). So, I'm no longer opposed to just copying it. I hope to split the megagraph in the next few days into smaller pieces (one subgraph per adapter and per chain). If you want, you can pick another ticket in the mean time.

**Comment by undermethod** [comment]
Meanwhile, I merged `Opty-Fi/megagraph:master` so as to at least alleviate previous errors from `RemoveLiquidityOne`

**Pull request closed without merging**
