### PR TITLE
OE-3: AaveV2 on Polygon

### PR DESCRIPTION
**Pull request by uwe**
Deployed to (but still syncing): https://thegraph.com/hosted-service/subgraph/opty-fi/aavev2-polygon?selected=logs

Based on the work of @kuririn1 #35

### CODE REVIEW

**Comment by uwe** [comment]
The subgraph stopped syncing (error), I'm investigating.

**Review by undermethod — COMMENTED** [review]
The only thing I could think of is the path `src/AaveV2/mappings/constants*.ts` with a symbolic link to [`constants.ts`](https://github.com/Opty-Fi/megagraph/blob/d0f9690f9728c9e108faa8f9a2185feb63e29b85/src/utils/constants.ts) (even though it's ignore [here](https://github.com/Opty-Fi/megagraph/pull/61/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R9)), along with the two `-ethereum` and `-polygon` varieties. No amount of playing around on my side causes a failure to codegen, build, or deploy, so I still don't know what leads to the sync failure, but perhaps this eventually interferes?

After all, the `src/utils/constants.ts` file has AaveV2 (1) Incentives Controller (1), but then both the symlink and `-polygon` have the (2) Pool Provider (2) and (3) Data Provider Index (3), so does the Polygon AaveV2 deploy have scope to these constants?

**Comment by uwe** [comment]
The Incentives Controller is used by Curve subgraph (and still WIP). Aave extra rewards are very complex.

**Comment by uwe** [comment]
The sync error only occurs after a certain block number. It is not an error that occurs immediately.

**Comment by undermethod** [comment]
> The sync error only occurs after a certain block number. It is not an error that occurs immediately.

Do you have the exact block number? You could try cross-referencing that block _(or that number ±1 block)_ to see if there's a Contract `startBlock` number in the `src/AaveV2/config/polygon.json` that's too early, and fails syncing because the it hasn't yet been deployed but attempts to access said Contract.

**Review by undermethod — APPROVED** [review]

**Pull request merged**
